language: go
go:
- 1.5.1
before_install:
- sudo mkdir --mode 0777 -p /var/ftp/incoming
- sudo apt-get install -qq vsftpd
- sudo cp $TRAVIS_BUILD_DIR/.vsftpd.conf /etc/vsftpd.conf
- sudo service vsftpd restart
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
script:
- $GOPATH/bin/goveralls -service=travis-ci
